version: "3.9"

services:
  # Main orchestrator - landing page
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    image: training-agentic-ai/orchestrator:latest
    env_file:
      - ./.env
    ports:
      - "8500:8500"
    environment:
      - STREAMLIT_SERVER_PORT=8500
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    depends_on:
      - customer-support-agent
      - legal-document-review
    networks:
      - agent-network

  # Legal Document Review Agent
  legal-document-review:
    build:
      context: .
      dockerfile: agents/legal-document-review/Dockerfile
    image: training-agentic-ai/legal-document-review:latest
    env_file:
      - ./.env
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./agents/legal-document-review/sample_documents:/app/sample_documents
    networks:
      - agent-network

  # Customer Support Agent
  customer-support-agent:
    build:
      context: .
      dockerfile: agents/customer-support-agent/Dockerfile
    image: training-agentic-ai/customer-support-agent:latest
    env_file:
      - ./.env
    ports:
      - "8502:8502"
    environment:
      - PYTHONPATH=/app/src
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge

